from __future__ import annotations

from typing import Protocol


class PersistenceBackend(Protocol):
    atomic_commits: bool

    def resolve_ref(self, ref: str) -> str: ...
    def read_file(self, commit_sha: str, path: str) -> bytes | None: ...
    def list_transaction_metadata(self, ref: str, transaction_id: str) -> list[dict[str, str]]: ...
    def create_commit_and_advance(self, *, ref: str, expected_base_sha: str, files: dict[str, bytes], message: str) -> str: ...
    def verify_commit(self, *, ref: str, commit_sha: str, expected_files: dict[str, bytes]) -> None: ...
    def read_commit_message(self, commit_sha: str) -> str: ...
